{
  "lineWidth": 120,
"tabWidth": 4,
"singleQuote": false,
"useTabs": false,
"plugins": [
"./node_modules/prettier-plugin-astro"
  ],
"overrides": [
    {
      "files": "*.astro",
"options": {
"parser": "astro"
      }
    }
  ]
}
